name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Upload XML test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: jasmine-xml-reports-node-${{ matrix.node-version }}
        path: test-reports/*.xml
        retention-days: 7
        
    - name: Upload results to Trunk
      # Run this step even if the test step ahead fails
      if: "!cancelled()"
      uses: trunk-io/analytics-uploader@main
      with:
        junit-paths: "test-reports/*.xml"
        # Provide your Trunk organization slug.
        org-slug: alex-test
        # Provide your Trunk API token as a GitHub secret.
        token: ${{ secrets.TRUNK_API_TOKEN }}
      continue-on-error: true
      
    - name: Build project
      run: npm run build
      
    - name: Test build output
      run: |
        echo "✅ Build completed successfully"
        echo "Build artifacts created in .next/ directory"
        ls -la .next/ || echo "No .next directory found"
